### ISSUE TITLE
Schemaspy6 error

### ISSUE THREAD

**Issue by tejeirodelrio** [claimvantage/force-metadata-jdbc-driver#3]
Hi,

I am running the following command:
java -jar schemaspy-6.0.0.jar -dp force-metadata-jdbc-driver-2.3.jar -debug -t force -u MyUser -p MyPassword -db MyDB -norows -o doc -connprops url\=https://test.salesforce.com/services/Soap/u/23.0 -cat % -s force

and I get ERROR - null. I have activated the debug to find out the line where it crashes.

INFO  - Starting Main v6.0.0 on LT18202 with PID 11484 (C:\Users\mtejeiro\Documents\sw\schemaspy6\schemaspy-6.0.0.jar started by mtejeiro in C:\Users\mtejeiro\Documents\sw\schemaspy6)
INFO  - The following profiles are active: default
INFO  - Started Main in 2.177 seconds (JVM running for 3.072)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: force ->
        /C:/Users/mtejeiro/Documents/sw/schemaspy6/force.properties
ForceMetaDataDriver: Force.com connection url https://test.salesforce.com/services/Soap/u/23.0
ForceMetaDataDriver: Filter [exclusionNames=[user], inclusionNames=[], keepCustom=true, keepStandard=false]
ERROR - null
java.lang.NullPointerException: null
        at org.schemaspy.service.DbmsService.lambda$fetchDbmsMeta$5(DbmsService.java:107)
        at org.schemaspy.service.DbmsService.onlyLogException(DbmsService.java:123)
        at org.schemaspy.service.DbmsService.fetchDbmsMeta(DbmsService.java:107)
        at org.schemaspy.service.SqlService.connect(SqlService.java:71)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:186)

With schemaspy 5, it works well but I would like to migrate to 6. Have you faced this issue or any clue about why it could fail?

Thanks,
Manuel

**Comment by tejeirodelrio** [comment]
Hey,

Not sure what I did but now it works.
I download your code instead of grabbing the .jar and compiled.
I am using now the following command:

java -jar schemaspy-6.0.0.jar -dp force-metadata-jdbc-driver-2.3.jar -debug -t force -u MyUser -p MyPassword -db MyDatabase -norows -s force -o doc -connprops url\=https://test.salesforce.com/services/Soap/u/23.0 -cat % -s force
